/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mperry' at '11/08/14 8:42 AM' with Gradle 2.0
 *
 * @author mperry, @date 11/08/14 8:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
